#!/bin/sh

. $UPATH/utils/func.sh

_help(){

    cat<<__EOF__
    Usage: u bluetooth [ status | enable | disable | help ]

    Examples:
      u bluetooth status         # bluetooth status
      u bluetooth start          # turn on bluetooth
      u bluetooth stop           # turn off bluetooth
      u bluetooth restart        # restart bluetooth
      u bluetooth force-reload   # force reload bluetooth
__EOF__

}

has_bluetooth()
{
	dmesg | grep -i blue > /dev/null 2>&1
}

if [ ! has_bluetooth ]; then
    echo "No bluetooth device!"
    exit 1
fi

case $1 in
    help)
        _help
        ;;
    status)
        _sudo_cmd /etc/init.d/bluetooth status
        ;;
    start)
        _sudo_cmd /etc/init.d/bluetooth start
        ;;
    stop)
        _sudo_cmd /etc/init.d/bluetooth stop
        ;;
    restart)
        _sudo_cmd /etc/init.d/bluetooth restart
        ;;
    force-reload)
        _sudo_cmd /etc/init.d/bluetooth force-reload
        ;;
    *)
        _help
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
