#!/bin/sh

. $UPATH/utils/func.sh

_help(){
    cat<<__EOF__
    usage: u dir [ chmod | tree | tree-size | delete | help ]

    Examples:
      u dir chmod -f /your/dir 644 # change all the files to 644 (-rw-r--r--) in /your/dir
      u dir chmod -d /your/dir 755 # change all the directories to 755 (-rwxr-xr-x) in /your/dir
      u dir tree                   # tree view of folders in the current path
      u dir tree-size              # tree view of folders in the current path with size
      u dir tree /your/dir         # tree view of folders in a specific path

      u dir delete empty           # delete empty folders recursively in the current path
      u dir delete empty /your/dir # delete empty folders recursively in a specific path

__EOF__

}

_tree_dirs(){
    tree $@
}

_tree_dirs_with_size(){
    tree -h $@
}

_delete_empty(){
    DIRS=${@:-.}
    echo "Folders to be deleted: "
    find $DIRS -type d -empty -print
    confirm && find $DIRS -type d -empty -delete
}



_delete(){
    case $1 in
        empty)
            shift;
            _delete_empty $@
            ;;
        *)
            _help && exit 1
            ;;
    esac
}

_chmod(){
    ROOT=$( pwd )
    case $1 in
    -f|f)
        find ${ROOT}/${2} -type f -exec chmod ${3} {} \;
        ;;
    -d|d)
        find ${ROOT}/${2} -type d -exec chmod ${3} {} \;
        ;;
    *)
        _help && exit 1
        ;;
    esac
}


case $1 in
    help)
        _help
        ;;
    chmod)
        shift
        _chmod "$@"
        ;;
    tree)
        shift
        _tree_dirs "$@"
        ;;
    tree-size)
        shift
        _tree_dirs_with_size "$@"
        ;;
    delete)
        shift;
        _delete "$@"
        ;;
    *)
        _help
        ;;
esac

