#!/bin/sh

. $UPATH/utils/func.sh

_help(){
    cat<<__EOF__
    usage: u dir [ tree | delete | help ]

    Examples:
      u dir tree                  # tree view of folders in the current path
      u dir tree-size             # tree view of folders in the current path with size
      u dir tree /path            # tree view of folders in a specific path

      u dir delete empty          # delete empty folders recursively in the current path
      u dir delete empty /path    # delete empty folders recursively in a specific path
__EOF__

}

_tree_dirs(){
    tree $@
}

_tree_dirs_with_size(){
    tree -h $@
}

_delete_empty(){
    DIRS=${@:-.}
    echo "Folders to be deleted: "
    find $DIRS -type d -empty -print
    confirm && find $DIRS -type d -empty -delete
}



_delete(){
    case $1 in
        empty)
            shift;
            _delete_empty $@
            ;;
        *)
            _help && exit 1
            ;;
    esac
}



case $1 in
    help)
        _help
        ;;
    tree)
        shift
        _tree_dirs $@
        ;;
    tree-size)
        shift
        _tree_dirs_with_size $@
        ;;
    delete)
        shift;
        _delete $@
        ;;
    *)
        _help
        ;;
esac

