#!/bin/sh

# TODO:
# * include a function to delete older directories by days or mins
# * include a function to delete newest directories by days or mins

. $UPATH/utils/func.sh

help(){
    cat<<__EOF__
    usage: u dir [ tree | delete | help ]

    Examples:
      u dir tree                  # tree view of folders in the current path
      u dir tree-size             # tree view of folders in the current path with size
      u dir tree /path            # tree view of folders in a specific path

      u dir delete empty          # delete empty folders recursively in the current path
      u dir delete empty /path    # delete empty folders recursively in a specific path
__EOF__

}

tree_dirs(){
    tree $@
}

tree_dirs_with_size(){
    tree -h $@
}

delete_empty(){
    DIRS=${@:-.}
    echo "Folders to be deleted: "
    find $DIRS -type d -empty -print
    confirm && find $DIRS -type d -empty -delete
}



delete(){
    case $1 in
        empty)
            shift;
            delete_empty $@
            ;;
        *)
            help && exit 1
            ;;
    esac
}



case $1 in
    help)
        help
        ;;
    tree)
        shift
        tree_dirs $@
        ;;
    tree-size)
        shift
        tree_dirs_with_size $@
        ;;
    delete)
        shift;
        delete $@
        ;;
    *)
        help
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
