#!/bin/sh


_help(){
    cat<<__EOF__
    Usage: u disk [ ls | list | info | help ]

    Examples:
      u disk ls                                 # list disks
      u disk list                               # list disks
      u disk list /dev/disk0                    # list a specific disk
      u disk info /dev/disk0                    # print info for a specific disk

__EOF__
}

disk_ls(){
    if [ -z "$1" ]; then
        df -h
    else
        df $1
    fi
}

disk_info(){
    [ -z "$1" ] && help && exit 1
    # enhace here
    df $1
}

case $1 in
    help)
        _help
        ;;
    list|ls)
        shift
        disk_ls "$@"
        ;;
    info)
        shift
        disk_info "$@"
        ;;
    *)
        _help
        ;;
esac

