#!/bin/sh

. $UPATH/utils/func.sh

help(){
    cat<<__EOF__
    Usage: u firewall [ status | enable | disable | help ]

    Examples:
       u firewall status                # Show status
       u firewall enable                # Enable firewall
       u firewall disable               # Disable firewall

__EOF__
}



case $1 in
    help)
        help
        ;;
    status)
        _sudo_cmd ufw status
        ;;
    enable)
        _sudo_cmd ufw enable
        ;;
    disable)
        _sudo_cmd ufw disable
        ;;
    *)
        help
        ;;
esac

