#!/bin/sh

. $UPATH/lib/functions.sh

help(){
    cat<<__EOF__
    usage: u firewall [ status | enable | disable | add | help ]

    Examples:
       u firewall status                # Show status
       u firewall enable                # Enable firewall
       u firewall disable               # Disable firewall
__EOF__
}



case $1 in
    help)
        help
        ;;
    status)
        _sudo_cmd ufw status
        ;;
    enable)
        _sudo_cmd ufw enable
        ;;
    disable)
        _sudo_cmd ufw disable
        ;;
    *)
        help
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
