#!/bin/sh

. $UPATH/utils/func.sh

_help(){
    cat<<__EOF__
    usage: u hostname [ help ]

    Examples:
      u hostname ls|list                 # get the current hostname information
      u hostname changeto                # set a new hostname
      u hostname help                    # only shows this help
__EOF__
}

case $1 in
    h|help)
        _help
        ;;
    ls|list)
        hostnamectl
        ;;
    changeto)
        if confirm "Want to change hostname[y/N](default NO)?";then
            read -r -p "New hostname: " _HOSTNAME
            [ -z ${_HOSTNAME} ] && echo "New hostname should not be none!" && exit 1
            hostnamectl ${_HOSTNAME}
            echo "Changing hostname to: ${_HOSTNAME}"
        else
            exit 1
        fi
        ;;
    *)
        _help
        ;;
esac
