#!/bin/sh


_help(){
    cat<<__EOF__
    usage: u hostname [ help ]

    Examples:
      u hostname                # get the current hostname information
      u hostname newhostname    # set a new hostname

      u hostname help           # only shows this help
__EOF__
}


show_hostname(){
    hostnamectl
}


set_hostname(){
    echo "Changing hostname to: $1"
    hostnamectl $1
}


case $1 in
    help)
        _help
        ;;
    *)
        if [ -z "$1" ]; then
            show_hostname
        else
            set_hostname $1
        fi
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
