#!/bin/sh

. $UPATH/utils/func.sh

_help()
{
    cat<<__EOF__
    Usage: u info [ help ]

    Examples:
      u info                     # print Operating System infomation
      u info cpu                 # print CPU infomation
      u info pci                 # print PCI infomation
      u info usb                 # print USB infomation
      u info disk                # print disk all the disk infomation
      u info diskinfo /my/disk   # print more about specific disk
      u info bios                # print BIOS infomation
      u info dmi                 # print DMI infomation
      u info hw|hardware         # Extract detailed information on the hardware configuration of the machine
      u info sw|os               # print Operating System infomation
      u info mem[ory]            # print memory infomation

__EOF__
}

case $1 in
    h|help)
        _help
        ;;
    # hardware
    [Cc][Pp][Uu])
        lscpu | more
        ;;
    [Pp][Cc][Ii])
        lspci | more
        ;;
    [Uu][Ss][Bb])
        lsusb | more
        ;;
    [Dd][Ii][Ss][Kk])
        df -H
        ;;
    diskinfo)
        shift
        [ -z $1 ] && _help && exit 1
        _sudo_cmd hdparm $1
        ;;
    [Bb][Ii][Oo][Ss])
        _sudo_cmd dmidecode -t bios | more
        ;;
    [Dd][Mm][Ii])
        _sudo_cmd dmidecode | more
        ;;
    hw|hardware)
        _sudo_cmd lshw | more
        ;;
    # software
    mem|memory)
        free -h
        ;;
    [Oo][Ss][Ss][Ww])
        lsb_release -a
        ;;
    *)
        lsb_release -a
        ;;
esac

