#!/bin/sh

. $UPATH/utils/sys/common.sh

help(){
    cat<<__EOF__
    usage: u info [ help ]

    Examples:
      u info                   #  print Ubuntu operating system version information
      u info hw|hardware       #  print HW DMI information
__EOF__
}

case $1 in
    help)
        help
        ;;

    hw|hardware)
        _sys_system_hw_info
        ;;
    *)
        _sys_system_sw_info
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
