#!/bin/sh

. $UPATH/utils/func.sh

_help()
{
    cat<<__EOF__
    usage: u info [ help ]

    Examples:
      u info                     # print Ubuntu operating system info
      u info cpu                 # print CPU info
      u info pci                 # print PCI info
      u info usb                 # print USB info
      u info disk                # print disk all the disk info
      u info diskinfo /my/disk   # print more about specific disk
      u info dmi                 # print DMI info
      u info hw|hardware         # Extract detailed information on the hardware configuration of the machine
      u info sw|os               # print Ubuntu operating system info
__EOF__
}

case $1 in
    h|help)
        _help
        ;;
    [Cc][Pp][Uu])
        lscpu | more
        ;;
    [Pp][Cc][Ii])
        lspci | more
        ;;
    [Uu][Ss][Bb])
        lsusb | more
        ;;
    [Dd][Ii][Ss][Kk])
        df -H
        ;;
    diskinfo)
        shift
        [ -z $1 ] && _help && exit 1
        _sudo_cmd hdparm $1
        ;;
    [Dd][Mm][Ii])
        _sudo_cmd dmidecode | more
        ;;
    hw|hardware)
        _sudo_cmd lshw | more
        ;;
    [Oo][Ss][Ss][Ww])
        lsb_release -a
        ;;
    *)
        lsb_release -a
        ;;
esac

