#!/bin/sh


. $UPATH/utils/func.sh
. $UPATH/utils/sys/common.sh

_help(){
    cat<<__EOF__
    Usage:  u ip [ all | help ]

    Examples:
      u ip help                  # show this help
      u ip                       # show your ip
      u ip a[all]                # list all your ip addr connected to remote server
__EOF__
}

case $1 in
    help)
        _help
        ;;
    *)
        _sys_show_ip $@
        ;;
esac

#https://www.mkyong.com/linux/list-all-ip-addresses-connected-to-your-server/
# vim: set ts=4 sw=4 softtabstop=4 expandtab
