#!/bin/sh

. $UPATH/utils/func.sh

_help(){
    cat<<__EOF__
    Usage:  u ip [ all | help ]

    Examples:
      u ip h[elp]                # show this help
      u ip                       # show your ip
      u ip a[all]                # list all your ip addr connected to remote server

__EOF__
}
_show_ip()
{
    case $1 in

       a|all)
           netstat -tn 2>/dev/null | more
       ;;
       *)
           netstat -tn 2>/dev/null \
           | grep tcp              \
           | grep \\.              \
           | awk '{print $4}'      \
           | cut -d: -f1           \
           | sort                  \
           | uniq -c               \
           | sort -nr              \
           | head                  \
           | awk '{print $2}'
       ;;
    esac
}

case $1 in
    h|help)
        _help
        ;;
    *)
        _show_ip $@
        ;;
esac

# Rfeference
# https://www.mkyong.com/linux/list-all-ip-addresses-connected-to-your-server/
