#!/bin/sh

. $UPATH/utils/func.sh

_help(){
    cat<<__EOF__
    Usage: u lock [ help ]

    Examples:
      u lock h[elp]       # show this help
      u lock              # lock the ubuntu

__EOF__
}

case $1 in
    -h|--help|h|help|-?|?)
        _help
        ;;
    *)
        gnome-screensaver-command --lock
        ;;
esac

