#!/bin/sh

. $UPATH/utils/func.sh

_help(){
    cat<<__EOF__
    Usage: u lock [ help ]

    Examples:
      u lock       # lock the ubuntu
__EOF__
}

case $1 in
    help)
        _help
        ;;
    *)
        gnome-screensaver-command --lock
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
