#!/bin/sh

. $UPATH/lib/functions.sh
. $UPATH/utils/proxy/set_proxy.sh
. $UPATH/utils/proxy/chk_proxy.sh

_help(){
    cat<<__EOF__
    usage:  u network [ ls | list | proxy | help ]

    Examples:
      u network ls                          # list network proxy
      u network proxy                       # get current proxy

      u network proxy none                  # set proxy mode none
      u network proxy man[ual]              # set proxy mode manual
      u network proxy auto                  # set proxy mode automatic
      u network proxy set                   # set a proxy
__EOF__

}


# change proxy to none/mamual/auto
_set_proxy_model()
{
	case $1 in
		none)
			echo " Set proxy mode - none"
			gsettings set org.gnome.system.proxy mode none
			auth=$(gsettings get org.gnome.system.proxy.http use-authentication)
			echo "Remove authentication credentials (id/password) saved on this system."
			if comfirm; then
                gsettings set org.gnome.system.proxy.http use-authentication false
                gsettings set org.gnome.system.proxy.http authentication-user "''"
                gsettings set org.gnome.system.proxy.http authentication-password "''"
            else
                _red_msg "Your login credentials still exist on this system"

                _red_msg "Take care! :)"
			fi
			echo "Operation completed successfully."
			;;

		man|manual)
			echo " Set proxy mode - manual"
			gsettings set org.gnome.system.proxy mode manual
			echo "Operation completed successfully."
			;;
		auto)
			echo " Set proxy mode - automatic"
			gsettings set org.gnome.system.proxy mode auto
			echo "Operation completed successfully."
			;;
        *)
			_help && exit 1;
	esac
}

_proxy(){
    case $1 in
        mode)
            [ -z "$2" ] && help && exit 1;
            shift
            _set_proxy_model $@
            ;;

        set)
            _proxy_set_proxy
            ;;

        list|ls)
            _proxy_chk_proxy
            ;;

        *)
            _help && exit 1;
            ;;
    esac
}


case $1 in
    help)
        _help
        ;;
    ls|list)
        list_netservices
        ;;
    proxy)
        shift
        _proxy $@
        ;;
    *)
        _help
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
