#!/bin/sh

. $UPATH/utils/func.sh

# TODO - remove below 2 files
. $UPATH/utils/proxy/set_proxy.sh
. $UPATH/utils/proxy/chk_proxy.sh

_help(){
    cat<<__EOF__
    Usage:  u proxy [ ls | list | none | man | auto | help ]

    Examples:
      u proxy ls                    # list network proxy
      u proxy help                  # show this help

      u proxy model none            # set proxy mode none
      u proxy model man             # set proxy mode manual
      u proxy model auto            # set proxy mode automatic
      u proxy set                   # set a proxy

__EOF__

}

#_list_netwrk()
#{
#    nmcli d
#}

# change proxy to none/mamual/auto
_set_proxy_model()
{
	case $1 in
		none)
			echo " Set proxy mode - none"
			gsettings set org.gnome.system.proxy mode none
			echo "Operation completed successfully."
			;;

		man|manual)
			echo " Set proxy mode - manual"
			gsettings set org.gnome.system.proxy mode manual
			echo "Operation completed successfully."
			;;
		auto)
			echo " Set proxy mode - automatic"
			gsettings set org.gnome.system.proxy mode auto
			echo "Operation completed successfully."
			;;
        *)
			_help && exit 1;
	esac
}

case $1 in
    help)
        _help
        ;;
    ls|list)
        _proxy_chk_proxy
        ;;
    mode)
        shift
        [ -z "$1" ] && help && exit 1;
        _set_proxy_model $@
        ;;

    set)
        _proxy_set_proxy
        ;;

    *)
        _help && exit 1;
        ;;
esac

