#!/bin/sh

. $UPATH/utils/func.sh

# TODO - remove below 2 files
. $UPATH/utils/proxy/set_proxy.sh

_help(){
    cat<<__EOF__
    Usage:  u proxy [ ls | list | none | man | auto | help ]

    Examples:
      u proxy help                  # show this help

      u proxy ls                    # list network proxy
      u proxy model none            # set proxy mode none
      u proxy model man             # set proxy mode manual
      u proxy model auto            # set proxy mode automatic
      u proxy set                   # set a proxy

__EOF__

}
_check_proxy()
{
    if [[ -e "$HOME/.bashrc" ]]; then
        a=$(grep -i proxy $HOME/.bashrc | wc -l)
        if [[ a -eq 0 ]]; then
            echo ".bashrc is not using proxy."
        else
            echo "For ~/.bashrc..."
            grep -i proxy $HOME/.bashrc
        fi
    else
        echo ".bashrc does not exist."
    fi

    if [[ -e "/etc/environment" ]]; then
        a=$(grep -i proxy /etc/environment | wc -l)
        if [[ a -eq 0 ]]; then
            echo "/etc/environment is not using proxy."
        else
            echo "For /etc/environment"
            grep -i proxy /etc/environment
        fi
    else
        echo "/etc/environment does not exist."
    fi

    if [[ -e "$HOME/.bash_profile" ]]; then
        a=$(grep -i proxy $HOME/.bash_profile | wc -l)
        if [[ a -eq 0 ]]; then
            echo ".bash_profile is not using proxy."
        else
            echo "For ~/.bash_profile..."
            grep -i proxy $HOME/.bash_profile
        fi
    else
        echo ".bash_profile does not exist."
    fi

    if [[ -e "/etc/apt/apt.conf" ]]; then
        echo "This is apt.conf ..."
        cat "/etc/apt/apt.conf"
    else
        echo "apt is not using proxy."
    fi

    mode=$(gsettings get org.gnome.system.proxy mode)
    if [[ $mode == "'none'" ]]; then
        echo "The desktop environment is not using any proxy settings."
        echo "Thus, gsettings configurations are ineffective."
    elif [[ $mode == "'manual'" ]]; then
        echo "The desktop environment is using manual proxy settings."
        echo "Thus, following gsettings configurations are effective."
        gsettings list-recursively org.gnome.system.proxy
    else
        echo "We cannot determine the type of settings. Sorry :("
    fi
}

# change proxy to none/mamual/auto
_set_proxy_model()
{
	case $1 in
		none)
			echo " Set proxy mode - none"
			gsettings set org.gnome.system.proxy mode none
			echo "Operation completed successfully."
			;;

		man|manual)
			echo " Set proxy mode - manual"
			gsettings set org.gnome.system.proxy mode manual
			echo "Operation completed successfully."
			;;
		auto)
			echo " Set proxy mode - automatic"
			gsettings set org.gnome.system.proxy mode auto
			echo "Operation completed successfully."
			;;
        *)
			_help && exit 1;
	esac
}

case $1 in
    help)
        _help
        ;;
    ls|list)
        _check_proxy
        ;;
    mode)
        shift
        [ -z "$1" ] && help && exit 1;
        _set_proxy_model $@
        ;;

    set)
        _proxy_set_proxy
        ;;

    *)
        _help && exit 1;
        ;;
esac

