#!/bin/sh

. $UPATH/utils/func.sh
. $UPATH/utils/proxy/set_proxy.sh
. $UPATH/utils/proxy/chk_proxy.sh

_help(){
    cat<<__EOF__
    usage:  u proxy [ ls | list | none | man | auto | help ]

    Examples:
      u proxy ls                    # list network proxy
      u proxy help                  # show this help

      u proxy model none            # set proxy mode none
      u proxy model man             # set proxy mode manual
      u proxy model auto            # set proxy mode automatic
      u proxy set                   # set a proxy
__EOF__

}

_list_netwrk()
{
    nmcli d
}
# change proxy to none/mamual/auto
_set_proxy_model()
{
	case $1 in
		none)
			echo " Set proxy mode - none"
			gsettings set org.gnome.system.proxy mode none
			auth=$(gsettings get org.gnome.system.proxy.http use-authentication)
			echo "Remove authentication credentials (id/password) saved on this system."
			if comfirm; then
                gsettings set org.gnome.system.proxy.http use-authentication false
                gsettings set org.gnome.system.proxy.http authentication-user "''"
                gsettings set org.gnome.system.proxy.http authentication-password "''"
            else
                _red_msg "Your login credentials still exist on this system"

                _red_msg "Take care! :)"
			fi
			echo "Operation completed successfully."
			;;

		man|manual)
			echo " Set proxy mode - manual"
			gsettings set org.gnome.system.proxy mode manual
			echo "Operation completed successfully."
			;;
		auto)
			echo " Set proxy mode - automatic"
			gsettings set org.gnome.system.proxy mode auto
			echo "Operation completed successfully."
			;;
        *)
			_help && exit 1;
	esac
}

_proxy(){
    case $1 in
        mode)
            [ -z "$2" ] && help && exit 1;
            shift
            _set_proxy_model $@
            ;;

        set)
            _proxy_set_proxy
            ;;

        list|ls)
            _proxy_chk_proxy
            ;;

        *)
            _help && exit 1;
            ;;
    esac
}


case $1 in
    help)
        _help
        ;;
    ls|list)
        _list_netwrk
        ;;
    mode)
        [ -z "$2" ] && help && exit 1;
        shift
        _set_proxy_model $@
        ;;

    set)
        _proxy_set_proxy
        ;;

    list|ls)
        _proxy_chk_proxy
        ;;

    *)
        _help && exit 1;
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
