#!/bin/sh

. $UPATH/utils/func.sh

help()
{
    cat<<__EOF__
    usage:  u  reboot [ -f | --force | help ]

    Examples:
      u reboot -f    # reboot computer (without confirmation)
      u reboot       # reboot computer (needs confirmation)
__EOF__
}
_force_reboot()
{
    _sudo_cmd reboot
}
_graceful_reboot()
{
    gnome-session-quit --reboot
}


case $1 in
    help)
        help
        ;;
    -f|--force)
        _force_reboot
        ;;
    *)
        _graceful_reboot
esac

