#!/bin/sh

. $UPATH/utils/func.sh

_help()
{
    cat<<__EOF__
    Usage:  u  reboot [ f | force | help ]

    Examples:
      u reboot h[elp]    # show this help
      u reboot f[orce]   # reboot computer (without confirmation)
      u reboot           # reboot computer (needs confirmation)

__EOF__
}
_force_reboot()
{
    _sudo_cmd reboot
}
_graceful_reboot()
{
    gnome-session-quit --reboot
}


case $1 in
    h|help)
        _help
        ;;
    f|force|-f|--force)
        _force_reboot
        ;;
    *)
        _graceful_reboot
esac

