#!/bin/sh

. $UPATH/utils/func.sh

_help(){
    cat<<__EOF__
    Usage:  u restart [ -f | --force | help ]

    Examples:
      u restart           # restart computer (needs confirmation)
      u restart -f[orce]  # restart computer (without confirmation)
__EOF__
}

_restart(){
    if confirm "Double confirm for restart, are you sure(Y/n)?"; then
        _sudo_cmd reboot
    else
        echo "Do nothing and safe EXIT" && exit 0
    fi
}

_force_restart(){
    _sudo_cmd reboot
}


case $1 in
    help)
        _help
        ;;
    -f|--force|force)
        _force_restart
        ;;
    *)
        _restart
        ;;
esac

# Reference
# [Restart in CLI](http://askubuntu.com/questions/187071/how-do-i-shut-down-or-reboot-from-a-terminal)
