#!/bin/sh

. $UPATH/utils/func.sh

_help(){
    cat<<__EOF__
    Usage: u service [ --status-all | list | ls | start | stop | restart | help ]


    Examples:
      u service h[elp]                              # show this help

      u service --status-all                        # list all services
      u service list                                # list all services
      u service ls                                  # list all services
      u service ls myservice                        # show status about a specific service

      u service start myservice                     # start a service
      u service stop myservice                      # stop a service

      u service restart myservice                   # start a service

__EOF__
}

service_list(){
    if [ -z "${1}" ]; then
        service --status-all
    else
         /etc/init.d/${1} status
    fi
}

service_start(){
    [ -z "${1}" ] && >&2 echo "Please enter servicename" && exit 1

    echo "Starting < ${1} >"
    _sudo_cmd /etc/init.d/${1} start
}

service_stop(){
    [ -z "${1}" ] && >&2 echo "Please enter servicename" && exit 1

    echo "Stoping < ${1} >"
    _sudo_cmd /etc/init.d/${1} stop
}

service_restart(){
    [ -z "${1}" ] && >&2 echo "Please enter servicename" && exit 1

    echo "Restart < ${1} >"
    _sudo_cmd /etc/init.d/${1} restart
}

case $1 in
    h|help)
        _help
        ;;
    --status-all|--list|--ls|list|ls)
        shift
        service_list $@
        ;;
    start)
        shift
        service_start $@
        ;;
    stop)
        shift
        service_stop $@
        ;;
    restart)
        shift
        service_restart $@
        ;;
    *)
        help
        ;;
esac

