#!/bin/sh

. $UPATH/utils/func.sh

_help(){
    cat<<__EOF__
    Usage:  u  shutdown [ f | force | help ]

    Examples:
      u shutdown h[elp]         # show this help
      u shutdown [--]f[orce]    # shutdown computer (without confirmation)
      u shutdown                # shutdown computer (needs confirmation)

__EOF__
}

_force_shutdown()
{
    _sudo_cmd poweroff
}

_graceful_shutdown()
{
    gnome-session-quit --reboot
}


case $1 in
    h|help)
        _help
        ;;
    f|force|-f|--force)
        _force_shutdown
        ;;
    *)
        _graceful_shutdown
esac

