#!/bin/sh

. $UPATH/utils/func.sh

help(){
    cat<<__EOF__
    usage:  u  shutdown [ -f | --force | help ]

    Examples:
      u shutdown f[orce]    # shutdown computer (without confirmation)
      u shutdown            # shutdown computer (needs confirmation)
__EOF__
}

_force_shutdown()
{
    _sudo_cmd poweroff
}

_graceful_shutdown()
{
    gnome-session-quit --reboot
}


case $1 in
    help)
        help
        ;;
    f|force)
        _force_shutdown
        ;;
    *)
        _graceful_shutdown
esac

