#!/bin/sh

. $UPATH/utils/func.sh

_help(){
    cat<<__EOF__
    Usage: u sleep [ help ]

    Examples:
      u sleep h[elp]      #  show this help
      u sleep             #  put the ubuntu to sleep/suspend

__EOF__
}

_force_sleep()
{
    _sudo_cmd pm-suspend
}

case $1 in
    h|help)
        _help
        ;;
    *)
        echo "Put ubuntu to sleep..."
        _force_sleep
        ;;
esac
