#!/bin/sh

. $UPATH/utils/func.sh
. $UPATH/utils/sys/common.sh

_help(){
    cat<<__EOF__
    Usage: u sleep [ help ]

    Examples:
      u sleep       #  put the ubuntu to sleep/suspend
__EOF__
}

case $1 in
    help)
        _help
        ;;
    *)
        echo "Put ubuntu to sleep..."
        _sys_force_sleep
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
