#!/bin/sh

. $UPATH/utils/func.sh


help(){
    cat<<__EOF__
    usage: m timezone [ list | ls | set | help ]

    Examples:
      m timezone                    # get current timezone
      m timezone ls                 # list available timezones
      m timezone set Europe/Berlin  # set timezone
__EOF__
}


case $1 in
    help)
        help
        ;;
    list|ls)

        ;;
    set)
        [ -z "$2" ] && help && exit 1;
        _sudo_cmd timedatectl set-timezone $2
        ;;
    *)
        cat /etc/timezone
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
