#!/bin/sh
#install trash-cli to improve this

. $UPATH/utils/sys/common.sh

_help(){
    cat<<__EOF__
    usage: u trash [ status | mv | clean | help ]

    Examples:
      u trash status         # get trash info
      u trash put filename   # move file to trash
      u trash list           # list file in trash
      u trash rm  filename   # remove one file in trash
      u trash restore        # restore file from trash for current path
      u trash clean[empty]   # clean trash
__EOF__
}

# check if trash-cli installed
# sudo apt-get install -y trash-cli
# src: https://github.com/andreafrancia/trash-cli
_sys_trash_cli_chk


case $1 in
    help)
        _help
        ;;
    status)
        _sys_trash_list
        ;;
    put)
       shift
       [ -z "$1" ] && _help  && exit 1
        _sys_trash_put $@
        ;;
    list)
        _sys_trash_list
        ;;
    rm)
        shift
        [ -z "$1" ] && _help  && exit 1
        _sys_trash_rm $@
        ;;
    restore)
        _sys_trash_restore
        ;;
    clean|empty)
        _sys_trash_clean
        ;;
    *)
        _help
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
