#!/bin/sh

. $UPATH/utils/func.sh

_help(){
    cat<<__EOF__
    Usage: u trash [ status | mv | clean | help ]

    Examples:
      u trash h[elp]         # show this help
      u trash status         # get trash info
      u trash put filename   # move file to trash
      u trash list           # list file in trash
      u trash rm  filename   # remove one file in trash
      u trash restore        # restore file from trash for current path
      u trash clean[empty]   # clean trash

__EOF__
}

_trash_cli_chk()
{
    if _has trash-list; then
        continue
    else
        echo "trash-cli is not installed, install it now?"
        if confirm; then
            clear
            echo "start to install trash-cli..."
            _sudo_cmd apt-get install trash-cli
            if _has trash-list; then

                echo "Done. Please re-run your command :)"
                exit 0
            else
                echo "ERROR encountered! Please have a check!"
                exit 1
            fi
        else
            echo "CMD \"u trash\" cannot be used without trash-cli :("
            exit 1
        fi
    fi
}

_trash_clean()
{
    trash-empty
}

_trash_clean()
{
    trash-empty
}

_trash_status()
{
    #[ -z "$1" ] && echo "No file!"  && exit 1
    trash-list

}
_trash_put()
{
    [ -z "$1" ] && echo "No file!"  && exit 1
    trash-put $@

}
_trash_list()
{
    #[ -z "$1" ] && echo "No file!"  && exit 1
    trash-list

}
_trash_clean()
{
#    [ ! -e "$HOME/.Trash"  ] && echo "Trash not found" && exit 1
    [ -z "$1" ] && echo "No file!"  && exit 1
    trash-empty
}
_trash_restore()
{
    [ -z "$1" ] && echo "No file!"  && exit 1
    trash-restore
}

# check if trash-cli installed
# sudo apt-get install -y trash-cli
_trash_cli_chk

case $1 in
    h|help)
        _help
        ;;
    status)
        _trash_list
        ;;
    put)
       shift
       [ -z "$1" ] && _help  && exit 1
        _trash_put $@
        ;;
    list)
        _trash_list
        ;;
    rm)
        shift
        [ -z "$1" ] && _help  && exit 1
        _trash_rm $@
        ;;
    restore)
        _trash_restore
        ;;
    clean|empty)
        _trash_clean
        ;;
    *)
        _help
        ;;
esac

# Reference
# https://github.com/andreafrancia/trash-cli
