#!/bin/sh

. $UPATH/utils/func.sh

_help(){

    cat<<__EOF__
    Usage: u volume [ + | - | mute | unmute ]

    Examples:
      u volume +              # increase volume by 5%
      u volume -              # decrease volume by 5%
      u volume mute           # volume mute
      u volume unmute         # volume unmute
__EOF__

}

case $1 in
    help)
        _help
        ;;
    \+)
        amixer -D pulse sset Master 5%+
        ;;
    \-)
        amixer -D pulse sset Master 5%-
        ;;
    mute)
        amixer set Master mute
        ;;
    unmute|umute)
        #amixer set Master unmute
        for x in `amixer controls  | grep layback > /dev/null 2>&1` ; do amixer cset "${x}" 70% > /dev/null 2>&1; done
        ;;
    *)
        _help
        ;;
esac

# Reference
# [unmute no work](http://askubuntu.com/questions/77522/command-to-unmute-and-maximize-volume)
