#!/bin/sh

. $UPATH/utils/func.sh

_help(){

    cat<<__EOF__
    Usage: u volume [ + | - | mute | unmute ]

    Examples:
      u volume +              # increase volume by 5%
      u volume -              # decrease volume by 5%
      u volume mute           # volume mute
      u volume unmute         # volume unmute
__EOF__

}

case $1 in
    help)
        _help
        ;;
    +)
        amixer -D pulse sset Master 5%+
        ;;
    -)
        amixer -D pulse sset Master 5%-
        ;;
    mute)
        amixer set Master mute
        ;;
    unmute)
        amixer set Master unmute
        ;;
    *)
        _help
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
