#!/bin/sh

. $UPATH/utils/sys/common.sh

_help(){
    cat<<__EOF__
    Usage: u wallpaper [ /path/to/file.jpg | help ]

    Examples:
      u wallpaper ./wallpapers/tree.jpg    # set wallpaper
__EOF__
}

case $1 in
    help)
        _help
        ;;
    *)
        [ -z "$1" ] && help && exit 1
        shift
        _sys_set_wallpaper $1
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
