#!/bin/sh
# iwconfig
# sudo ifconfig wlan0 down
# sudo ifconfig wlan0 up

. $UPATH/utils/func.sh

_W_DEVICE=$(nmcli d | grep wireless | awk '{ print $1 }')

_help(){
    cat<<__EOF__
    Usage:  u wifi [ status | scan | off | on | connect | disconnect | passwd | help ]

    Examples:
      u wifi status                   # wifi status
      u wifi scan                     # scan wifi
      u wifi off                      # turn off your wifi
      u wifi on                       # turn on your wifi
      u wifi connect SSID PASSWORD    # connect a wifi network
      u wifi disconnect [SSID]        # disconnect current wifi network
      u wifi [show]passw[or]d [SSID]  # show wifi network password
__EOF__
}

wifi_status()
{
    nmcli nm wifi
}

wifi_scan()
{
    _sudo_cmd "iw dev $_W_DEVICE scan | grep SSID"
}

wifi_showpassword()
{
    if [ -z "$1" ]; then
        ssid=`wifi_scan | grep SSID | awk '{print $2}'`
        passwd=$(_sudo_cmd grep psk= /etc/NetworkManager/system-connections/$ssid | awk -F = '{print $2}')
    else
        passwd=`_sudo_cmd grep psk= /etc/NetworkManager/system-connections/$1`
    fi
    cat<<__EOF__
    SSID     : $ssid
    password : $passwd
__EOF__
}

wifi_off(){
    nmcli nm wifi off
}


wifi_on(){
    nmcli nm wifi on
}

connect_network(){
    [ -z "$1" -o -z "$2" ] && help
    nmcli d wifi connect $1 password $2 iface $_W_DEVICE
}

disconnect_network(){
    if [ -z "$1" ]; then
        ssid=`wifi_scan | grep SSID | awk '{print $2}'`
    else
        ssid=$1
    fi

    nmcli d disconnect iface $ssid
}

case $1 in
    help)
        _help
        ;;
    scan)
        wifi_scan
        ;;
    status)
        wifi_status
        ;;
    off)
        wifi_off
        ;;
    on)
        wifi_on
        ;;
    connect)
        shift
        connect_network "$@"
        ;;
    disconnect)
        shift
        disconnect_network "$@"
        ;;
    showpassword|showpasswd|password|passwd)
        shift
        wifi_showpassword "$@"
        ;;
    *)
        _help
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
